### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by KaylanTRCH** [MilesAddie/sem#6]
Tasks defined as user stories

**Comment by radinkaman** [comment]
As a < user role >, I can < activity > so that < business value >.

- User role is who the story involves. It needs to be specific enough to allow a conversation. User is not a legitimate user role.
- Activity is the task the user wants or is required to do.
- Business value is why the task is important.

Example:
As a wheelchair user I want to go into the computer lab so that I can do my assignment on a lab computer.
